[package]
name = "ttri"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.32"
vulkano-shaders = "0.32"
vulkano-win = "0.32"
nalgebra = "0.31"
winit = "0.27"

bytemuck = "1.12"
image = "0.24"

ttri_model = {path = "../ttri_model"}
