[package]
name = "ttri"
version = "0.1.0"
edition = "2021"

[dependencies]
vulkano = "0.32"
bytemuck = "1.12"
image = "0.24"

ttri_model = {path = "../ttri_model"}
rust_stddep = {path = "../rust_stddep", features = ["nalgebra", "winit"]}
